GCNode* newString(char* str);
int len(GCNode* node);
int asc(GCNode* node);
GCNode* chr(int txt);
GCNode* int2string(int value);
GCNode* float2string(float value);
GCNode* double2string(double value);
GCNode* short2string(short value);
GCNode* long2string(long value);
GCNode* byte2string(char value);
int string2int(GCNode* node);
float string2float(GCNode* node);
double string2double(GCNode* node);
short string2short(GCNode* node);
long string2long(GCNode* node);
char string2byte(GCNode* node);
GCNode* joinstr(GCNode* node1, GCNode* node2);
int instr(GCNode* node1, GCNode* node2, int start);
GCNode* mid(GCNode* node, int von, int bis);
GCNode* left(GCNode* str, int anzahl);
GCNode* right(GCNode* str, int anzahl);
GCNode* upper(GCNode* node);
GCNode* lower(GCNode* node);
GCNode* replace(GCNode* str1, GCNode* str2, GCNode* str3, int start);
GCNode* trim(GCNode* node);
char* toCString(GCNode* node);
